### ISSUE TITLE
Help me with Magick.NET?

### ISSUE THREAD

**Issue by dlemstra** [stepperman/MagickSharp#1]
I saw that you tried Magick.NET with .NET Core and found out that it did not work cross platform yet. Would you be willing to help me to make it cross platform? I have an issue that explains what I need: https://github.com/dlemstra/Magick.NET/issues/16. You would help me a lot if you could assist me in creating a build script that I could use on a *nix platform. Once that is done it should not be a lot of work to make the calls to the libraries from Magick.NET. We can also have a chat if you need some more information.

**Comment by gwnvisje** [comment]
I'm not sure I have the required Linux experience to make a proper build script.  
I just started learning C, including how to compile in Linux and all. I'm sure it's not _that_ hard and I could have a look.  

For example, a problem I'm stuck with is how to bring the shared library into the `/usr/lib` folder on Linux, since it doesn't search the current directory for lib files.

**Comment by gwnvisje** [comment]
@dlemstra It seems I can't debug the project because I am missing the debug libs. Where can I get these? They weren't in the Dropbox.

**Comment by dlemstra** [comment]
You will need to build them yourself. The "build scripts" for the debug version are here: https://github.com/dlemstra/Magick.NET/tree/master/ImageMagick/Source/Debug

**Comment by gwnvisje** [comment]
I've tried doing that, but I seem to be having missing files.

```Powershell
Exception calling "ReadAllText" with "2" argument(s): "Could not find a part of the path 'D:\game dev\!Visual Studio\Ma
gick.NET\ImageMagick\Source\ImageMagick\libxml\include\libxml\xmlversion.h'."
At D:\game dev\!Visual Studio\Magick.NET\Tools\Scripts\BuildLibraries.ps1:235 char:3
+   $xmlversion = [IO.File]::ReadAllText($xmlversionFile, [System.Text. ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DirectoryNotFoundException

Exception calling "WriteAllText" with "3" argument(s): "Could not find a part of the path 'D:\game dev\!Visual Studio\M
agick.NET\ImageMagick\Source\ImageMagick\libxml\include\libxml\xmlversion.h'."
At D:\game dev\!Visual Studio\Magick.NET\Tools\Scripts\BuildLibraries.ps1:242 char:3
+   [IO.File]::WriteAllText($xmlversionFile, $xmlversion, [System.Text. ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DirectoryNotFoundException

Cannot locate a solution file.
Set-Location : Cannot find path 'D:\game dev\!Visual Studio\Magick.NET\ImageMagick\Source\ImageMagick\VisualMagick\conf
igure' because it does not exist.
At D:\game dev\!Visual Studio\Magick.NET\Tools\Scripts\Shared\Functions.ps1:23 char:3
+   Set-Location $directory
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\game dev\!Vi...agick\configure:String) [Set-Location], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

Microsoft (R) Build Engine version 14.0.24728.2
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: configure.sln
CheckExitCode : Failed to build: D:\game dev\!Visual Studio\Magick.NET\ImageMagick\Source\ImageMagick\VisualMagick\conf
igure\configure.sln
At D:\game dev\!Visual Studio\Magick.NET\Tools\Scripts\Shared\Functions.ps1:26 char:3
+   CheckExitCode "Failed to build: $($path)"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,CheckExitCode```

**Comment by dlemstra** [comment]
You will need to run the CheckOut.cmd command. More information on how to build the ImageMagick part can be found here: https://github.com/dlemstra/Magick.NET/blob/master/Building.md

**Comment by gwnvisje** [comment]
No matter what I try, I can't seem to properly build the debug files. When running checkout.cmd it gives me an error saying `MagickCore/version.h` does not exist, when I rename it and run it again nothing happens. When I build all I get the same error message saying `configure.sln does not exist`. How do I fix this?

**Comment by gwnvisje** [comment]
@dlemstra Is it possible if you could help me with this?

**Comment by dlemstra** [comment]
Of course, do you have Skype? Might be easier to explain then. Did you follow the installation instructions in the Building.md file?

**Comment by gwnvisje** [comment]
@dlemstra Yeah I do, although I don't use it I suppose I can stay online for a while. My username is moviemaker310. I'll wait for you to add me
